run:
  timeout: 5m
  go: "1.26"

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - gocritic
    - gosec

linters-settings:
  revive:
    rules:
      - name: exported
      - name: package-comments
      - name: var-naming
  gosec:
    excludes:
      - G104 # errcheck handles
  goimports:
    local-prefixes: github.com/albedosehen/surql-go

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
